name: CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest # Specifies to run the job on the latest Ubuntu runner.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out the repository code.

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ssh_server }} # Your server IP or hostname, stored as a secret.
        username: ${{ secrets.ssh_username }} # SSH username, stored as a secret.
        password: ${{ secrets.ssh_password }} # SSH password, stored as a secret.
        port: 22 # Optional. Default SSH port 22 is used unless changed.
        script: |
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          docker stop fastapi-app
          docker rm fastapi-app
          docker build -t fastapi-app .
          docker run -d --name fastapi-app -p 8000:8000 fastapi-app


